name       : python-pytest-flake8
version    : 1.0.2
release    : 2
source     :
    - https://pypi.io/packages/source/p/pytest-flake8/pytest-flake8-1.0.2.tar.gz : c740ad6aa19e3958947d2118f70bed218caf1d2097039fb7318573a2a72f89a1
license    : BSD-2-Clause
component  : programming.python
summary    : pytest plugin to run flake8
description: |
    pytest plugin for efficiently checking PEP8 compliance
builddeps  :
    - flake8
    - python-pytest
    - python-setuptools
rundeps    :
    - flake8
    - python-pytest
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test pytest
