name       : python-pytest-flake8
version    : 1.0.3
release    : 4
source     :
    - https://pypi.io/packages/source/p/pytest-flake8/pytest-flake8-1.0.3.tar.gz : b2c71fb6d469bae076a01c43d4a83485d740db6a8a00bad77e0657ed035e98d4
license    : BSD-2-Clause
component  : programming.python
summary    : pytest plugin to run flake8
description: |
    pytest plugin for efficiently checking PEP8 compliance
builddeps  :
    - flake8
    - python-pytest
    - python-setuptools
rundeps    :
    - flake8
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest -v
    %python3_test pytest3 -v
