name       : python-pytest-flake8
version    : 0.9.1
release    : 1
source     :
    - https://pypi.io/packages/source/p/pytest-flake8/pytest-flake8-0.9.1.tar.gz : e716072d07a557defdd5c4141984569731e292961370a5663c1697283aa16200
license    : BSD-2-Clause
component  : programming.python
summary    : pytest plugin to run flake8
description: |
    pytest plugin for efficiently checking PEP8 compliance
builddeps  :
    - flake8
    - python-pytest
    - python-setuptools
rundeps    :
    - flake8
    - python-pytest
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test -v -k 'not test_keyword_match'
    popd
