name       : python-pytest-flake8
version    : 1.0.4
release    : 6
source     :
    - https://files.pythonhosted.org/packages/f0/b5/e1360bfe5b1218fe4f7a7fd6038de8d990e980c6f5d55c922e216de7131b/pytest-flake8-1.0.4.tar.gz : 4d225c13e787471502ff94409dcf6f7927049b2ec251c63b764a4b17447b60c0
license    : BSD-2-Clause
component  : programming.python
summary    : pytest plugin to run flake8
description: |
    pytest plugin for efficiently checking PEP8 compliance
builddeps  :
    - flake8
    - python-pytest
    - python-setuptools
rundeps    :
    - flake8
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test pytest -v
#    %python3_test pytest3 -v
