name       : python-pytest-flake8
version    : 1.0.7
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-flake8/pytest-flake8-1.0.7.tar.gz : f0259761a903563f33d6f099914afef339c085085e643bee8343eb323b32dd6b
homepage   : https://github.com/tholo/pytest-flake8
license    : BSD-2-Clause
component  : programming.python
summary    : pytest plugin to run flake8
description: |
    pytest plugin for efficiently checking PEP8 compliance
builddeps  :
    - flake8
    - python-pytest
rundeps    :
    - flake8
    - python-pytest
setup      : |
    %patch -p1 < $pkgfiles/Remove-Python2-support-and-dependency-on-py.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
